module vtkwriter
    implicit none

    private
    public :: writer

    type writer
        private
        character(len=64) :: filename
        character(len=64) :: version = "# vtk DataFile Version 3.0"
        character(len=256) :: header = "generated by vtkwriter"
        character(len=16) :: format = "ASCII"
        character(len=32) :: dataset = "UNSTRUCTURED_GRID"
        logical :: active = .false.
    contains
        procedure :: init
        procedure :: write1d
        procedure :: write2d
    end type writer

contains
    subroutine init(self, filename)
        class(writer) :: self
        character(len=*) :: filename
        self%filename = filename
        self%active = .false.
    end subroutine


    subroutine write1d(self, x, dims, vname, value)
        class(writer) :: self
        character(len=*) :: vname
        real(kind=8) :: x(:), value(:)
        integer(kind=4) :: dims
        integer(kind=4) :: points_num, cells_num, cells_num_in_list
        real(kind=8) :: width
        integer(kind=4) :: I
        character(len=256) :: str

        if (.not. self%active) then
            self%active = .true.
            width = maxval(x)/10
            points_num = dims*2
            cells_num = 1
            cells_num_in_list = points_num + 1

            open(10, file=self%filename, status='replace')
            write(10, '(A64)') self%version
            write(10, '(A256)') self%header
            write(10, '(A16)') self%format
            write(10, '("DATASET ", A32)') self%dataset
            write(10, *) ""

            ! POINTS [Points#] [DataType]
            write(10, '("POINTS ", I8, A8)')  points_num, "double"
            do I = 1, dims
                write(str, *) x(I), 0., 0.
                write(10, '(A64)') adjustl(str)
                write(str, *) x(I), width, 0.
                write(10, '(A64)') adjustl(str)
            end do
            write(10, *) ""

            ! CELLS [Cells#] [Cells#_inList]
            write(10, '("CELLS ", I8, I8)') cells_num, cells_num_in_list
            write(str, *) points_num
            write(10, '(A8)', advance='no') adjustl(str)
            do I = 1, points_num
                write(10, '(I8)', advance='no') I - 1
            end do
            write(10, *) ""
            write(10, *) ""
            
            ! CELL_TYPES [Cells#] -> VTK_TRIANGLE_STRIP(6)
            write(10, '("CELL_TYPES ", I8)') cells_num
            write(str, *) 6
            write(10, '(A2)') adjustl(str)
            write(10, *) ""

            ! POINT_DATA [Points#]
            write(10, '("POINT_DATA ", I8)') points_num
            write(10, *) ""

        else
            open(10, file=self%filename, status='old', position='append')   
        end if
        
        ! SCALARS [DataName] [DataType] [NumComp]
        write(10, '("SCALARS ", A16, A8, I2)') vname, "double", 1
        write(10, '("LOOKUP_TABLE ", A32)') vname//"_table"
        do I = 1, dims
            write(str, *) value(I)
            write(10, '(A32)') adjustl(str)
            write(10, '(A32)') adjustl(str)
        end do
        write(10, *) ""
        close(10)
    end subroutine


    subroutine write2d(self, x, y, dims, vname, value)
        class(writer) :: self
        character(len=*) :: vname
        real(kind=8) :: x(:), y(:), value(:)
        integer(kind=4) :: dims(2)
        integer(kind=4) :: points_num, cells_num, cells_num_in_list
        integer(kind=4) :: I ,J
        character(len=256) :: str

        if (.not. self%active) then
            self%active = .true.
            points_num = dims(1)*dims(2)
            cells_num = (dims(2) - 1)*(dims(1) - 1)
            cells_num_in_list = cells_num*5

            open(10, file=self%filename, status='replace')
            write(10, '(A64)') self%version
            write(10, '(A256)') self%header
            write(10, '(A16)') self%format
            write(10, '("DATASET ", A32)') self%dataset
            write(10, *) ""
            
            ! POINTS [Points#] [DataType]
            write(10, '("POINTS ", I8, A8)') points_num, "double"
            do I = 1, points_num
                write(str, *) x(I), y(I), 0.
                write(10, '(A64)') adjustl(str)
            end do
            write(10, *) ""

            ! CELLS [Cells#] [Cells#_inList]
            write(10, '("CELLS ", I8, I8)') cells_num, cells_num_in_list
            do J = 1, dims(2) - 1
                do I = 1, dims(1) - 1
                    write(str, *) 4
                    write(10, '(A2)', advance='no') adjustl(str)
                    write(10, '(I8)', advance='no') I - 1 + (J - 1)*dims(1)
                    write(10, '(I8)', advance='no') I + (J - 1)*dims(1)
                    write(10, '(I8)', advance='no') I - 1 + J*dims(1)
                    write(10, '(I8)') I + J*dims(1)
                end do
            end do
            write(10, *) ""

            ! CELL_TYPES [Cells#] -> VTK_PIXEL(8)
            write(10, '("CELL_TYPES ", I8)') cells_num
            do J = 1, dims(2) - 1
                do I = 1, dims(1) - 1
                    write(str, *) 8
                    write(10, '(A2)') adjustl(str)
                end do
            end do
            write(10, *) ""

            ! POINT_DATA [Points#]
            write(10, '("POINT_DATA ", I8)') points_num
            write(10, *) ""

        else
            open(10, file=self%filename, status='old', position='append')
        end if
        
        ! SCALARS [DataName] [DataType] [NumComp]
        write(10, '("SCALARS ", A16, A8, I2)') vname, "double", 1
        write(10, '("LOOKUP_TABLE ", A32)') vname//"_table"
        do I = 1, points_num
            write(str, *) value(I)
            write(10, '(A8)') adjustl(str)
        end do
        write(10, *) ""
        close(10)
    end subroutine

end module